apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello-war
  name: hello-war
spec:
  ports:
  - port: 8999
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-war
  type: NodePort
status:
  loadBalancer: {}
